title: Lawrence's Website
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://aixcee08.github.io/website/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
